name: Build

#on:
#  workflow_dispatch

on:
  push:
    branches:
      - main

jobs:
  SmokeTests:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
        config: [Debug, Release]
        include:
          - os: macos-15
            name: macOS
          - os: ubuntu-24.04
            name: Linux
          - os: windows-2025
            name: Windows

    steps:

      - name: Set VCPKG_ROOT and VCPKG_PATH (Windows Release)
        if: ${{ (runner.os == 'Windows') && (matrix.config == 'Release') }}
        run: |
           echo "VCPKG_ROOT=${{ github.workspace }}\..\vcpkg" >> "$env:GITHUB_ENV"
           echo "VCPKG_PATH=${{ github.workspace }}\..\vcpkg\installed\x64-windows" >> "$env:GITHUB_ENV"

      - name: Set VCPKG_ROOT and VCPKG_PATH (Windows Debug)
        if: ${{ (runner.os == 'Windows') && (matrix.config == 'Debug') }}
        run: |
           echo "VCPKG_ROOT=${{ github.workspace }}\..\vcpkg" >> "$env:GITHUB_ENV"
           echo "VCPKG_PATH=${{ github.workspace }}\..\vcpkg\installed\x64-windows\debug" >> "$env:GITHUB_ENV"

      - name: Set paths (Windows)
        if: runner.os == 'Windows'
        run: |
           echo "$env:VCPKG_ROOT\installed\x64-windows\tools\pkgconf" >> "$env:GITHUB_PATH"
           echo "${{ github.workspace }}\build\${{ matrix.config }}" >> "$env:GITHUB_PATH"
           echo "$env:VCPKG_PATH\bin" >> "$env:GITHUB_PATH"
           echo "PKG_CONFIG_PATH=$env:VCPKG_PATH\lib\pkgconfig" >> "$env:GITHUB_ENV"

      - name: Check paths (Windows)
        if: runner.os == 'Windows'
        run: |
           echo "PATH=$env:PATH"
           echo "VCPKG_ROOT=$env:VCPKG_ROOT"
           echo "VCPKG_PATH=$env:VCPKG_PATH"
           echo "PKG_CONFIG_PATH=$env:PKG_CONFIG_PATH"

      - name: Prerequisites (Windows)
        if: runner.os == 'Windows'
        run: |
           cd ..
           git clone https://github.com/Microsoft/vcpkg --depth=1
           cd vcpkg; cmd /c bootstrap-vcpkg.bat
           vcpkg install pkgconf
           vcpkg install gmp

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: |
           pwd
           cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DMINI_GMP_PLUS_WITH_TESTS=1

      - name: Build
        run: cmake --build build --config ${{ matrix.config }}

      - name: Test
        run: |
            echo $PATH
            cd build/tests; ctest -C ${{ matrix.config }}
